# Generated by Django 2.2.12 on 2020-07-29 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=datetime.datetime(2020, 7, 29, 8, 55, 40, 946903, tzinfo=utc), max_length=50, verbose_name='product category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default=datetime.datetime(2020, 7, 29, 8, 56, 1, 352658, tzinfo=utc), max_length=50, verbose_name='product producer'),
            preserve_default=False,
        ),
    ]
